name: event_app
description: An Event App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.1
  comment_box: ^0.0.18
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.1.6
  flutter_toggle_tab: ^1.4.1
  hooks_riverpod: ^2.3.6
  http: ^0.13.5
  image_picker: ^1.0.4
  intl: ^0.18.0
  table_calendar: ^3.0.9
  google_sign_in: ^5.2.1
  
#   comment_box: ^0.0.18
#   firebase_core: ^2.16.0
#   firebase_auth: ^4.10.0
#   google_sign_in: ^6.1.5




dev_dependencies:
  custom_lint: ^0.5.3
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.1.0



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
